spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/general_data?useUnicode=yes&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none
server:
  port: 8081
#dolphin:
#  security:
#    browser:
#      loginType: REDIRECT
#      loginPage: /demo-signIn.html