spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/general_data?useUnicode=yes&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none
server:
  port: 8081
dolphin:
  security:
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessesUrl: /qqLogin
    browser:
      signUrl: /demo-signUp.html
#    # 应用级配置
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user,/user/*
#    browser:
#      loginType: REDIRECT
#      loginPage: /demo-signIn.html